### ISSUE TITLE
Unable to fetch mapping. Do you have indices matching the pattern?

### ISSUE THREAD

**Issue by earthquakesan** [big-data-europe/app-http-logger#2]
I am running the following:
```
docker-compose up
```
And then this docker-compose.yml:
```
version: "2"
services:
  nginx:
    image: nginx
    labels:
      - "logging=true"
    environment:
      - "logging=true"
    ports:
      - 13337:80
```

When I open Kibana it redirects me to "Configure an index pattern" screen, where I define "hars*" as written in README. However, I can not create an index pattern: Unable to fetch mapping. Do you have indices matching the pattern?

What am I missing? (I am testing everything on local docker engine, no swarm)
